# Non-secret environment configuration. Secrets never live in this file:
# the database password and APP_KEY are generated by Terraform and stored
# only in Secret Manager and in the (access-controlled) remote state.

image              = "africa-south1-docker.pkg.dev/cashonrails-live/cashonrails/api:bootstrap"
deployer_email     = "github-deployer@cashonrails-live.iam.gserviceaccount.com"
notification_email = "soundnwankwo@gmail.com"

# Assessment sizing. Production sizing decisions are documented in
# docs/architecture/architecture.md.
db_tier       = "db-f1-micro"
min_instances = 0
max_instances = 4
